```sql
-- =====================================================
-- 10. DDL
-- 1. Common
-- =====================================================

CREATE TABLE EMPLOYEE (
    EMPLOYEE_SEQ BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMPLOYEE_ID VARCHAR(20) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    EMPLOYEE_NM VARCHAR(100) NOT NULL,
    DEPT_CD VARCHAR(50) NOT NULL,
    POSITION_CD VARCHAR(50) NULL,
    BIRTH_DT DATE NULL,
    PHONE_NO VARCHAR(255) NULL,
    EMERGENCY_PHONE_NO VARCHAR(255) NULL,
    EMAIL VARCHAR(100) NULL,
    ZIP_CODE VARCHAR(10) NULL,
    ADDRESS VARCHAR(255) NULL,
    DETAIL_ADDRESS VARCHAR(255) NULL,
    HIRE_DT DATE NULL,
    RETIRE_DT DATE NULL,
    EMPLOYEE_STATUS_CD VARCHAR(50) NOT NULL,
    LOGIN_FAIL_CNT INT NOT NULL DEFAULT 0,
    LOGIN_LOCK_YN CHAR(1) NOT NULL DEFAULT 'N',
    LOGIN_LOCK_DT DATETIME NULL,
    PASSWORD_CHANGE_DT DATETIME NULL,
    CREATE_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATE_ID VARCHAR(20) NOT NULL,
    UPDATE_DT DATETIME NULL,
    UPDATE_ID VARCHAR(20) NULL,
    UNIQUE KEY UK_EMPLOYEE_EMPLOYEE_ID (EMPLOYEE_ID)
);

CREATE TABLE EMPLOYEE_HISTORY (
    EMPLOYEE_HISTORY_SEQ BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMPLOYEE_ID VARCHAR(20) NOT NULL,
    ACTION_CD VARCHAR(50) NOT NULL,
    PROCESS_ID VARCHAR(20) NOT NULL,
    PROCESS_DEPT_CD VARCHAR(50) NULL,
    PROCESS_DT DATETIME NOT NULL,
    PROCESS_COMMENT VARCHAR(500) NULL,
    CREATE_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATE_ID VARCHAR(20) NOT NULL
);

CREATE TABLE DEPARTMENT (
    DEPT_SEQ BIGINT AUTO_INCREMENT PRIMARY KEY,
    DEPT_CD VARCHAR(50) NOT NULL,
    DEPT_NM VARCHAR(100) NOT NULL,
    PARENT_DEPT_CD VARCHAR(50) NULL,
    DEPT_LEVEL INT NOT NULL,
    SORT_ORDER INT NOT NULL DEFAULT 0,
    DEPT_CREATE_DT DATE NULL,
    DEPT_CLOSE_DT DATE NULL,
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y',
    CREATE_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATE_ID VARCHAR(20) NOT NULL,
    UPDATE_DT DATETIME NULL,
    UPDATE_ID VARCHAR(20) NULL,
    UNIQUE KEY UK_DEPARTMENT_DEPT_CD (DEPT_CD)
);

CREATE TABLE ROLE (
    ROLE_SEQ BIGINT AUTO_INCREMENT PRIMARY KEY,
    ROLE_CD VARCHAR(50) NOT NULL,
    ROLE_NM VARCHAR(100) NOT NULL,
    ROLE_DESC VARCHAR(500) NULL,
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y',
    CREATE_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATE_ID VARCHAR(20) NOT NULL,
    UPDATE_DT DATETIME NULL,
    UPDATE_ID VARCHAR(20) NULL,
    UNIQUE KEY UK_ROLE_ROLE_CD (ROLE_CD)
);

CREATE TABLE EMPLOYEE_ROLE (
    EMPLOYEE_ROLE_SEQ BIGINT AUTO_INCREMENT PRIMARY KEY,
    ROLE_CD VARCHAR(50) NOT NULL,
    EMPLOYEE_ID VARCHAR(20) NOT NULL,
    CREATE_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATE_ID VARCHAR(20) NOT NULL,
    UNIQUE KEY UK_EMPLOYEE_ROLE (ROLE_CD, EMPLOYEE_ID)
);

CREATE TABLE MENU (
    MENU_SEQ BIGINT AUTO_INCREMENT PRIMARY KEY,
    MENU_CD VARCHAR(50) NOT NULL,
    MENU_NM VARCHAR(100) NOT NULL,
    PARENT_MENU_CD VARCHAR(50) NULL,
    MENU_LEVEL INT NOT NULL,
    MENU_URL VARCHAR(255) NULL,
    SORT_ORDER INT NOT NULL DEFAULT 0,
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y',
    CREATE_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATE_ID VARCHAR(20) NOT NULL,
    UPDATE_DT DATETIME NULL,
    UPDATE_ID VARCHAR(20) NULL,
    UNIQUE KEY UK_MENU_MENU_CD (MENU_CD)
);

CREATE TABLE MENU_ROLE (
    MENU_ROLE_SEQ BIGINT AUTO_INCREMENT PRIMARY KEY,
    MENU_CD VARCHAR(50) NOT NULL,
    ROLE_CD VARCHAR(50) NOT NULL,
    CREATE_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATE_ID VARCHAR(20) NOT NULL,
    UNIQUE KEY UK_MENU_ROLE (MENU_CD, ROLE_CD)
);

CREATE TABLE CODE_GROUP (
    CODE_GROUP_SEQ BIGINT AUTO_INCREMENT PRIMARY KEY,
    CODE_GROUP_CD VARCHAR(50) NOT NULL,
    CODE_GROUP_NM VARCHAR(100) NOT NULL,
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y',
    CREATE_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATE_ID VARCHAR(20) NOT NULL,
    UPDATE_DT DATETIME NULL,
    UPDATE_ID VARCHAR(20) NULL,
    UNIQUE KEY UK_CODE_GROUP_CD (CODE_GROUP_CD)
);

CREATE TABLE CODE_DETAIL (
    CODE_DETAIL_SEQ BIGINT AUTO_INCREMENT PRIMARY KEY,
    CODE_GROUP_CD VARCHAR(50) NOT NULL,
    CODE_DETAIL_CD VARCHAR(50) NOT NULL,
    CODE_DETAIL_NM VARCHAR(100) NOT NULL,
    SORT_ORDER INT NOT NULL DEFAULT 0,
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y',
    CREATE_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATE_ID VARCHAR(20) NOT NULL,
    UPDATE_DT DATETIME NULL,
    UPDATE_ID VARCHAR(20) NULL,
    UNIQUE KEY UK_CODE_DETAIL (CODE_GROUP_CD, CODE_DETAIL_CD)
);

CREATE TABLE FILE (
    FILE_SEQ BIGINT AUTO_INCREMENT PRIMARY KEY,
    FILE_REF_NO VARCHAR(50) NOT NULL,
    ORIGINAL_FILE_NM VARCHAR(255) NOT NULL,
    STORED_FILE_NM VARCHAR(255) NOT NULL,
    FILE_PATH VARCHAR(500) NOT NULL,
    FILE_EXT VARCHAR(20) NULL,
    FILE_SIZE BIGINT NOT NULL DEFAULT 0,
    PRIVACY_YN CHAR(1) NOT NULL DEFAULT 'N',
    CREATE_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATE_ID VARCHAR(20) NOT NULL,
    INDEX IDX_FILE_REF_NO (FILE_REF_NO)
);

CREATE TABLE NOTIFICATION (
    NOTIFICATION_SEQ BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOTIFICATION_CD VARCHAR(50) NOT NULL,
    BIZ_CD VARCHAR(50) NOT NULL,
    SENDER_ID VARCHAR(20) NULL,
    RECEIVER_ID VARCHAR(20) NOT NULL,
    TITLE VARCHAR(200) NOT NULL,
    CONTENT VARCHAR(1000) NULL,
    READ_YN CHAR(1) NOT NULL DEFAULT 'N',
    FIRST_READ_DT DATETIME NULL,
    CREATE_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATE_ID VARCHAR(20) NOT NULL,
    INDEX IDX_NOTIFICATION_RECEIVER (RECEIVER_ID, READ_YN),
    INDEX IDX_NOTIFICATION_BIZ (BIZ_CD)
);
```
```sql
-- =====================================================
-- 2. SR
-- =====================================================

CREATE TABLE SR (
    SR_SEQ BIGINT AUTO_INCREMENT PRIMARY KEY,
    SR_NO VARCHAR(30) NOT NULL,
    SR_TITLE VARCHAR(200) NOT NULL,
    SR_CONTENT TEXT NOT NULL,
    SR_CATEGORY_CD VARCHAR(50) NULL,
    SR_PRIORITY_CD VARCHAR(50) NULL,
    REQUEST_ID VARCHAR(20) NOT NULL,
    REQUEST_DEPT_CD VARCHAR(50) NOT NULL,
    ASSIGNEE_ID VARCHAR(20) NULL,
    SR_STATUS_CD VARCHAR(50) NOT NULL,
    DUE_DT DATE NULL,
    COMPLETE_DT DATETIME NULL,
    FILE_REF_NO VARCHAR(50) NULL,
    CREATE_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATE_ID VARCHAR(20) NOT NULL,
    UPDATE_DT DATETIME NULL,
    UPDATE_ID VARCHAR(20) NULL,
    UNIQUE KEY UK_SR_NO (SR_NO),
    INDEX IDX_SR_STATUS (SR_STATUS_CD),
    INDEX IDX_SR_REQUEST (REQUEST_ID),
    INDEX IDX_SR_ASSIGNEE (ASSIGNEE_ID),
    INDEX IDX_SR_DUE_DT (DUE_DT)
);

CREATE TABLE SR_HISTORY (
    SR_HISTORY_SEQ BIGINT AUTO_INCREMENT PRIMARY KEY,
    SR_SEQ BIGINT NOT NULL,
    SR_NO VARCHAR(30) NOT NULL,
    ACTION_CD VARCHAR(50) NOT NULL,
    PROCESS_ID VARCHAR(20) NOT NULL,
    PROCESS_DEPT_CD VARCHAR(50) NULL,
    PROCESS_DT DATETIME NOT NULL,
    PROCESS_COMMENT VARCHAR(500) NULL,
    CREATE_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATE_ID VARCHAR(20) NOT NULL,
    INDEX IDX_SR_HISTORY_SR_SEQ (SR_SEQ),
    INDEX IDX_SR_HISTORY_SR_NO (SR_NO),
    INDEX IDX_SR_HISTORY_PROCESS_DT (PROCESS_DT)
);

CREATE TABLE SR_UAT (
    SR_UAT_SEQ BIGINT AUTO_INCREMENT PRIMARY KEY,
    SR_SEQ BIGINT NOT NULL,
    UAT_ORDER INT NOT NULL,
    REQUEST_ID VARCHAR(20) NOT NULL,
    REQUEST_DT DATETIME NOT NULL,
    TEST_METHOD TEXT NULL,
    TEST_CONTENT TEXT NULL,
    REQUEST_FILE_REF_NO VARCHAR(50) NULL,
    RESULT_ID VARCHAR(20) NULL,
    RESULT_DT DATETIME NULL,
    TEST_RESULT TEXT NULL,
    RESULT_FILE_REF_NO VARCHAR(50) NULL,
    UAT_STATUS_CD VARCHAR(50) NOT NULL,
    REJECT_REASON VARCHAR(1000) NULL,
    DEV_MANAGER_CONFIRM_ID VARCHAR(20) NULL,
    DEV_MANAGER_CONFIRM_DT DATETIME NULL,
    CREATE_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATE_ID VARCHAR(20) NOT NULL,
    UPDATE_DT DATETIME NULL,
    UPDATE_ID VARCHAR(20) NULL,
    INDEX IDX_SR_UAT_SR_SEQ (SR_SEQ),
    INDEX IDX_SR_UAT_STATUS (UAT_STATUS_CD),
    UNIQUE KEY UK_SR_UAT_ORDER (SR_SEQ, UAT_ORDER)
);

CREATE TABLE SANC (
    SANC_SEQ BIGINT AUTO_INCREMENT PRIMARY KEY,
    BIZ_CD VARCHAR(50) NOT NULL,
    TARGET_SEQ BIGINT NOT NULL,
    CURRENT_STEP_CD VARCHAR(50) NOT NULL,
    SANC_STATUS_CD VARCHAR(50) NOT NULL,
    CREATE_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATE_ID VARCHAR(20) NOT NULL,
    UPDATE_DT DATETIME NULL,
    UPDATE_ID VARCHAR(20) NULL,
    INDEX IDX_SANC_TARGET (BIZ_CD, TARGET_SEQ),
    INDEX IDX_SANC_STATUS (SANC_STATUS_CD)
);

CREATE TABLE SANC_DETAIL (
    SANC_DETAIL_SEQ BIGINT AUTO_INCREMENT PRIMARY KEY,
    SANC_SEQ BIGINT NOT NULL,
    SANC_STEP_CD VARCHAR(50) NOT NULL,
    SANC_ACTION_CD VARCHAR(50) NOT NULL,
    PROCESS_ID VARCHAR(20) NOT NULL,
    PROCESS_DEPT_CD VARCHAR(50) NULL,
    PROCESS_DT DATETIME NOT NULL,
    PROCESS_COMMENT VARCHAR(500) NULL,
    CREATE_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATE_ID VARCHAR(20) NOT NULL,
    INDEX IDX_SANC_DETAIL_SANC_SEQ (SANC_SEQ),
    INDEX IDX_SANC_DETAIL_PROCESS_DT (PROCESS_DT)
);
```
```sql
-- =====================================================
-- 3. HR
-- =====================================================

CREATE TABLE EMPLOYEE_REGISTRATION (
    EMPLOYEE_REGISTRATION_SEQ BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMPLOYEE_NM VARCHAR(100) NOT NULL,
    DEPT_CD VARCHAR(50) NOT NULL,
    BIRTH_DT DATE NULL,
    PHONE_NO VARCHAR(255) NULL,
    EMERGENCY_PHONE_NO VARCHAR(255) NULL,
    EMAIL VARCHAR(100) NULL,
    ZIP_CODE VARCHAR(10) NULL,
    ADDRESS VARCHAR(255) NULL,
    DETAIL_ADDRESS VARCHAR(255) NULL,
    REGISTRATION_STATUS_CD VARCHAR(50) NOT NULL,
    FILE_REF_NO VARCHAR(50) NULL,
    CREATE_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATE_ID VARCHAR(20) NOT NULL,
    UPDATE_DT DATETIME NULL,
    UPDATE_ID VARCHAR(20) NULL,
    INDEX IDX_EMP_REG_STATUS (REGISTRATION_STATUS_CD),
    INDEX IDX_EMP_REG_DEPT (DEPT_CD),
    INDEX IDX_EMP_REG_CREATE_DT (CREATE_DT)
);

CREATE TABLE EMPLOYEE_REGISTRATION_HISTORY (
    EMPLOYEE_REGISTRATION_HISTORY_SEQ BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMPLOYEE_REGISTRATION_SEQ BIGINT NOT NULL,
    ACTION_CD VARCHAR(50) NOT NULL,
    PROCESS_ID VARCHAR(20) NOT NULL,
    PROCESS_DEPT_CD VARCHAR(50) NULL,
    PROCESS_DT DATETIME NOT NULL,
    PROCESS_COMMENT VARCHAR(500) NULL,
    CREATE_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATE_ID VARCHAR(20) NOT NULL,
    INDEX IDX_EMP_REG_HIST_REG_SEQ (EMPLOYEE_REGISTRATION_SEQ),
    INDEX IDX_EMP_REG_HIST_PROCESS_DT (PROCESS_DT)
);
```
```sql
-- =====================================================
-- 4. FACILITY
-- =====================================================

CREATE TABLE FACILITY (
    FACILITY_SEQ BIGINT AUTO_INCREMENT PRIMARY KEY,
    FACILITY_CD VARCHAR(50) NOT NULL,
    FACILITY_TYPE_CD VARCHAR(50) NOT NULL,
    FACILITY_NM VARCHAR(100) NOT NULL,
    LOCATION VARCHAR(255) NULL,
    CAPACITY INT NULL,
    DESCRIPTION VARCHAR(1000) NULL,
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y',
    CREATE_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATE_ID VARCHAR(20) NOT NULL,
    UPDATE_DT DATETIME NULL,
    UPDATE_ID VARCHAR(20) NULL,
    UNIQUE KEY UK_FACILITY_CD (FACILITY_CD),
    INDEX IDX_FACILITY_TYPE (FACILITY_TYPE_CD),
    INDEX IDX_FACILITY_USE_YN (USE_YN)
);

CREATE TABLE FACILITY_RESERVATION (
    FACILITY_RESERVATION_SEQ BIGINT AUTO_INCREMENT PRIMARY KEY,
    FACILITY_SEQ BIGINT NOT NULL,
    RESERVATION_NO VARCHAR(30) NOT NULL,
    RESERVATION_CONTENT TEXT NULL,
    REQUEST_ID VARCHAR(20) NOT NULL,
    REQUEST_DEPT_CD VARCHAR(50) NOT NULL,
    START_DT DATETIME NOT NULL,
    END_DT DATETIME NOT NULL,
    RESERVATION_STATUS_CD VARCHAR(50) NOT NULL,
    FILE_REF_NO VARCHAR(50) NULL,
    CREATE_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATE_ID VARCHAR(20) NOT NULL,
    UPDATE_DT DATETIME NULL,
    UPDATE_ID VARCHAR(20) NULL,
    UNIQUE KEY UK_RESERVATION_NO (RESERVATION_NO),
    INDEX IDX_FACILITY_SEQ (FACILITY_SEQ),
    INDEX IDX_REQUEST_ID (REQUEST_ID),
    INDEX IDX_RESERVATION_STATUS (RESERVATION_STATUS_CD),
    INDEX IDX_RESERVATION_DATE (START_DT, END_DT)
);
```
```sql
-- =====================================================
-- 5. EAPP
-- =====================================================

CREATE TABLE EAPP_DOCUMENT (
    EAPP_DOCUMENT_SEQ BIGINT AUTO_INCREMENT PRIMARY KEY,
    EAPP_TYPE_CD VARCHAR(50) NOT NULL,
    EAPP_TITLE VARCHAR(200) NOT NULL,
    EAPP_CONTENT TEXT NOT NULL,
    REQUEST_ID VARCHAR(20) NOT NULL,
    REQUEST_DEPT_CD VARCHAR(50) NOT NULL,
    EAPP_STATUS_CD VARCHAR(50) NOT NULL,
    FILE_REF_NO VARCHAR(50) NULL,
    CREATE_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATE_ID VARCHAR(20) NOT NULL,
    UPDATE_DT DATETIME NULL,
    UPDATE_ID VARCHAR(20) NULL,
    INDEX IDX_EAPP_TYPE (EAPP_TYPE_CD),
    INDEX IDX_EAPP_STATUS (EAPP_STATUS_CD),
    INDEX IDX_EAPP_REQUEST (REQUEST_ID),
    INDEX IDX_EAPP_CREATE_DT (CREATE_DT)
);

CREATE TABLE EAPP_LINE (
    EAPP_LINE_SEQ BIGINT AUTO_INCREMENT PRIMARY KEY,
    EAPP_DOCUMENT_SEQ BIGINT NOT NULL,
    LINE_TYPE_CD VARCHAR(50) NOT NULL,
    LINE_ORDER INT NOT NULL,
    EMPLOYEE_ID VARCHAR(20) NOT NULL,
    LINE_STATUS_CD VARCHAR(50) NOT NULL,
    PROCESS_DT DATETIME NULL,
    PROCESS_ID VARCHAR(20) NULL,
    CREATE_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATE_ID VARCHAR(20) NOT NULL,
    UPDATE_DT DATETIME NULL,
    UPDATE_ID VARCHAR(20) NULL,
    INDEX IDX_EAPP_LINE_DOC (EAPP_DOCUMENT_SEQ),
    INDEX IDX_EAPP_LINE_EMPLOYEE (EMPLOYEE_ID),
    INDEX IDX_EAPP_LINE_PROCESS (PROCESS_ID),
    INDEX IDX_EAPP_LINE_STATUS (LINE_STATUS_CD),
    UNIQUE KEY UK_EAPP_LINE_ORDER (EAPP_DOCUMENT_SEQ, LINE_TYPE_CD, LINE_ORDER)
);
```
```sql
-- =====================================================
-- 6. LOG
-- =====================================================

CREATE TABLE SYSTEM_LOG (
    SYSTEM_LOG_SEQ BIGINT AUTO_INCREMENT PRIMARY KEY,
    BIZ_CD VARCHAR(50) NOT NULL,
    ACTION_CD VARCHAR(50) NOT NULL,
    URI VARCHAR(500) NULL,
    PROCESS_ID VARCHAR(20) NULL,
    PROCESS_DEPT_CD VARCHAR(50) NULL,
    PROCESS_DT DATETIME NOT NULL,
    PROCESS_COMMENT VARCHAR(500) NULL,
    IP VARCHAR(50) NULL,
    EXECUTE_TIME BIGINT NULL,
    CREATE_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATE_ID VARCHAR(20) NULL,
    INDEX IDX_SYSTEM_LOG_BIZ (BIZ_CD),
    INDEX IDX_SYSTEM_LOG_PROCESS (PROCESS_ID),
    INDEX IDX_SYSTEM_LOG_PROCESS_DT (PROCESS_DT)
);

CREATE TABLE ERROR_LOG (
    ERROR_LOG_SEQ BIGINT AUTO_INCREMENT PRIMARY KEY,
    BIZ_CD VARCHAR(50) NULL,
    URI VARCHAR(500) NULL,
    ERROR_CODE VARCHAR(50) NULL,
    ERROR_MESSAGE VARCHAR(1000) NULL,
    STACK_TRACE LONGTEXT NULL,
    PROCESS_ID VARCHAR(20) NULL,
    PROCESS_DT DATETIME NOT NULL,
    IP VARCHAR(50) NULL,
    CREATE_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATE_ID VARCHAR(20) NULL,
    INDEX IDX_ERROR_LOG_BIZ (BIZ_CD),
    INDEX IDX_ERROR_LOG_CODE (ERROR_CODE),
    INDEX IDX_ERROR_LOG_PROCESS_DT (PROCESS_DT)
);

CREATE TABLE DOWNLOAD_LOG (
    DOWNLOAD_LOG_SEQ BIGINT AUTO_INCREMENT PRIMARY KEY,
    FILE_SEQ BIGINT NOT NULL,
    FILE_REF_NO VARCHAR(50) NOT NULL,
    BIZ_CD VARCHAR(50) NOT NULL,
    DOCUMENT_NO VARCHAR(50) NULL,
    DOWNLOAD_ID VARCHAR(20) NOT NULL,
    DOWNLOAD_DT DATETIME NOT NULL,
    CREATE_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATE_ID VARCHAR(20) NOT NULL,
    INDEX IDX_DOWNLOAD_LOG_FILE (FILE_SEQ),
    INDEX IDX_DOWNLOAD_LOG_REF (FILE_REF_NO),
    INDEX IDX_DOWNLOAD_LOG_USER (DOWNLOAD_ID),
    INDEX IDX_DOWNLOAD_LOG_DT (DOWNLOAD_DT)
);

CREATE TABLE PERSONAL_INFO_ACCESS_LOG (
    PERSONAL_INFO_ACCESS_LOG_SEQ BIGINT AUTO_INCREMENT PRIMARY KEY,
    BIZ_CD VARCHAR(50) NOT NULL,
    ACCESS_TYPE VARCHAR(50) NOT NULL,
    TARGET_ID VARCHAR(20) NOT NULL,
    TARGET_NM VARCHAR(100) NULL,
    ACCESS_ID VARCHAR(20) NOT NULL,
    REQUEST_URI VARCHAR(500) NULL,
    IP VARCHAR(50) NULL,
    CREATE_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATE_ID VARCHAR(20) NOT NULL,
    INDEX IDX_PERSONAL_INFO_TARGET (TARGET_ID),
    INDEX IDX_PERSONAL_INFO_ACCESS (ACCESS_ID),
    INDEX IDX_PERSONAL_INFO_CREATE_DT (CREATE_DT)
);

CREATE TABLE FILE_DELETE_LOG (
    FILE_DELETE_LOG_SEQ BIGINT AUTO_INCREMENT PRIMARY KEY,
    FILE_SEQ BIGINT NOT NULL,
    FILE_REF_NO VARCHAR(50) NOT NULL,
    ORIGINAL_FILE_NM VARCHAR(255) NOT NULL,
    STORED_FILE_NM VARCHAR(255) NOT NULL,
    FILE_PATH VARCHAR(500) NOT NULL,
    DELETE_DT DATETIME NOT NULL,
    DELETE_ID VARCHAR(20) NOT NULL,
    DELETE_RESULT VARCHAR(50) NOT NULL,
    ERROR_MESSAGE VARCHAR(1000) NULL,
    CREATE_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATE_ID VARCHAR(20) NOT NULL,
    INDEX IDX_FILE_DELETE_FILE (FILE_SEQ),
    INDEX IDX_FILE_DELETE_REF (FILE_REF_NO),
    INDEX IDX_FILE_DELETE_DT (DELETE_DT)
);

CREATE TABLE BATCH_LOG (
    BATCH_LOG_SEQ BIGINT AUTO_INCREMENT PRIMARY KEY,
    BATCH_CD VARCHAR(50) NOT NULL,
    START_DT DATETIME NOT NULL,
    END_DT DATETIME NULL,
    RESULT VARCHAR(50) NOT NULL,
    SUCCESS_COUNT INT NOT NULL DEFAULT 0,
    FAIL_COUNT INT NOT NULL DEFAULT 0,
    MESSAGE VARCHAR(1000) NULL,
    CREATE_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATE_ID VARCHAR(20) NULL,
    INDEX IDX_BATCH_LOG_CD (BATCH_CD),
    INDEX IDX_BATCH_LOG_START_DT (START_DT),
    INDEX IDX_BATCH_LOG_RESULT (RESULT)
);
```
